%% Add paths

addpath('bh_tsne');
addpath('tSNE_matlab');


%% Parameter variables. Change these values HERE

params = struct(...
    'descriptor',    'DSIFT',...  % SIFT, DSIFT, SF_GABOR, ST_GABOR, ST_GAUSS,
    'corridors',     [1:6],... % Corridors to run [1:6] (RSM v6.0)
    'passes',        [1:10],... % Passes to run [1:10] (RSM v6.0)
    'datasetDir',    'dataset/location/to/be/defined/',...   % The root path of the RSM dataset
    'trainingPassesPerCorr', 4, ...
    'trainingSet', [7 4 8 3], ...
    'frameDir',      'frames_resized_w208p',... % Folder name where all the frames have been extracted.
    'descrDir',  ...
    '/descriptor/location/to/be/defined/', ...
    'dictionarySize', 4000, ...
    'dictPath',       './data/dictionaries', ...
    'encoding', 'HA', ... % 'HA', 'VLAD'
    'debug', 1 ... % 1 shows waitbars, 0 does not.
    );